version: 0.2

env:
  variables:
    REGION: "us-east-1"
    ACCOUNT_ID: "908027380341"
    ECR_REPO_NAME: "task-app"
    REPORT_BUCKET: "ecr-scan-reports-908027380341"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$ECR_REPO_NAME
      - echo "REPOSITORY_URI=$REPOSITORY_URI"
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "IMAGE_TAG=$IMAGE_TAG"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Waiting for scan results...
      - |
        for i in {1..10}; do
          STATUS=$(aws ecr describe-image-scan-findings \
            --repository-name $ECR_REPO_NAME \
            --image-id imageTag=$IMAGE_TAG \
            --region $REGION \
            --query 'imageScanStatus.status' --output text)
          echo "Scan status: $STATUS"
          if [[ "$STATUS" == "COMPLETE" ]]; then break; fi
          sleep 10
        done
      - echo Getting scan findings...
      - aws ecr describe-image-scan-findings --repository-name $ECR_REPO_NAME --image-id imageTag=$IMAGE_TAG --region $REGION > scan-findings.json
      - cat scan-findings.json | jq
      - echo Uploading scan report to S3...
      - TIMESTAMP=$(date +%s)
      - aws s3 cp scan-findings.json s3://$REPORT_BUCKET/scan-findings-$TIMESTAMP.json
      - |
        HIGH_OR_CRITICAL=$(jq '[.imageScanFindings.findings[] | select(.severity=="HIGH" or .severity=="CRITICAL")] | length' scan-findings.json)
        echo "$HIGH_OR_CRITICAL high/critical vulnerabilities found."
        if [ "$HIGH_OR_CRITICAL" -gt 0 ]; then
          echo "Failing the build due to high/critical vulnerabilities."
          exit 1
        fi

artifacts:
  files:
    - scan-findings.json