version: 0.2

env:
  variables:
    ECR_REPO_NAME: "task-app"
    IMAGE_TAG: "latest"
    REGION: "us-east-1"
    REPORT_BUCKET: "ecr-scan-reports-908027380341"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPO_URI=$(aws ecr describe-repositories --repository-names $ECR_REPO_NAME --region $REGION --query "repositories[0].repositoryUri" --output text)
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPO_URI

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Waiting for scan results...
      - |
        for i in {1..10}; do
          STATUS=$(aws ecr describe-image-scan-findings \
            --repository-name $ECR_REPO_NAME \
            --image-id imageTag=$IMAGE_TAG \
            --region $REGION \
            --query 'imageScanStatus.status' --output text)
          echo "Scan status: $STATUS"
          if [[ "$STATUS" == "COMPLETE" ]]; then break; fi
          sleep 10
        done
      - echo Getting scan findings...
      - aws ecr describe-image-scan-findings \
          --repository-name $ECR_REPO_NAME \
          --image-id imageTag=$IMAGE_TAG \
          --region $REGION > scan-findings.json
      - cat scan-findings.json | jq
      - |
        HIGH_OR_CRITICAL=$(jq '[.imageScanFindings.findings[] | select(.severity=="HIGH" or .severity=="CRITICAL")] | length' scan-findings.json)
        echo "$HIGH_OR_CRITICAL high/critical vulnerabilities found."
        if [ "$HIGH_OR_CRITICAL" -gt 0 ]; then
          echo "Failing the build due to high/critical vulnerabilities."
          aws s3 cp scan-findings.json s3://$REPORT_BUCKET/scan-findings-$(date +%s).json
          exit 1
        fi
artifacts:
  files:
    - scan-findings.json